import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { CONFIG_DIR } from "./paths.js";

const FEEDBACK_FILE = join(CONFIG_DIR, "feedback.json");

interface FeedbackConfig {
    feedbackHintShown: boolean;
}

function readFeedbackConfig(): FeedbackConfig {
    try {
        if (!existsSync(FEEDBACK_FILE)) return { feedbackHintShown: false };
        const data = readFileSync(FEEDBACK_FILE, "utf-8");
        return JSON.parse(data) as FeedbackConfig;
    } catch {
        return { feedbackHintShown: false };
    }
}

function writeFeedbackConfig(config: FeedbackConfig): void {
    try {
        const dir = dirname(FEEDBACK_FILE);
        if (!existsSync(dir)) {
            mkdirSync(dir, { recursive: true });
        }
        writeFileSync(FEEDBACK_FILE, JSON.stringify(config, null, 2));
    } catch {
        // Best-effort — silent fail
    }
}

export function shouldShowFeedbackHint(): boolean {
    return !readFeedbackConfig().feedbackHintShown;
}

export function markFeedbackHintShown(): void {
    const config = readFeedbackConfig();
    config.feedbackHintShown = true;
    writeFeedbackConfig(config);
}

// ============================================================================
// Issue Formatting
// ============================================================================

// Last-resort slug. The repo has been renamed once already (react-native-ai-devtools →
// execbro), and the hardcoded copy of the old name outlived the rename here, so the slug is
// read from package.json — the one place a rename is guaranteed to update.
const FALLBACK_GITHUB_REPO = "igorzheludkov/execbro";

/** Reduce a GitHub clone/issues/homepage URL to its `owner/repo` slug. */
export function parseRepoSlug(url: unknown): string | undefined {
    if (typeof url !== "string") return undefined;
    const match = url.match(/github\.com[/:]([^/]+)\/([^/#?]+)/);
    if (!match) return undefined;
    return `${match[1]}/${match[2].replace(/\.git$/, "")}`;
}

export function getGitHubRepo(): string {
    try {
        const here = dirname(fileURLToPath(import.meta.url));
        const pkg = JSON.parse(readFileSync(join(here, "..", "..", "package.json"), "utf-8"));
        return parseRepoSlug(pkg?.bugs?.url) ?? parseRepoSlug(pkg?.repository?.url) ?? FALLBACK_GITHUB_REPO;
    } catch {
        return FALLBACK_GITHUB_REPO;
    }
}

interface FeedbackInput {
    type: "feedback" | "feature_request" | "bug";
    title: string;
    description: string;
    workflowContext?: string;
}

interface EnvironmentInfo {
    serverVersion: string;
    platform: string;
    deviceType: string | undefined;
    licenseTier: string;
}

export function formatIssueBody(input: FeedbackInput, env: EnvironmentInfo): string {
    const lines: string[] = [];

    lines.push("## Feedback");
    lines.push(input.description);
    lines.push("");
    lines.push("## Workflow Context");
    lines.push(input.workflowContext || "N/A");
    lines.push("");
    lines.push("## Environment");
    lines.push("| Key | Value |");
    lines.push("|-----|-------|");
    lines.push(`| Server Version | ${env.serverVersion} |`);
    lines.push(`| Platform | ${env.platform} |`);
    lines.push(`| Device | ${env.deviceType || "not connected"} |`);
    lines.push(`| License | ${env.licenseTier} |`);
    lines.push("");
    lines.push("---");
    lines.push(`*Generated by ExecBro v${env.serverVersion} via \`send_feedback\`*`);

    return lines.join("\n");
}

export function buildGitHubUrl(title: string, type: FeedbackInput["type"]): string {
    const labelMap: Record<FeedbackInput["type"], string> = {
        bug: "bug",
        feature_request: "enhancement",
        feedback: "feedback",
    };
    const label = labelMap[type];
    const params = new URLSearchParams({
        title,
        labels: label,
    });
    return `https://github.com/${getGitHubRepo()}/issues/new?${params.toString()}`;
}
